let strip = neopixel.create(DigitalPin.P15, 2, NeoPixelMode.RGB)
let left = strip.range(0, 1)
let right = strip.range(1, 1)
basic.forever(function () {
    left.showColor(neopixel.colors(NeoPixelColors.Red))
    cuteBot.singleheadlights(cuteBot.RGBLights.RGB_R, 255, 0, 0)
    basic.pause(500)
    left.showColor(neopixel.colors(NeoPixelColors.Black))
    cuteBot.singleheadlights(cuteBot.RGBLights.RGB_R, 0, 0, 0)
    basic.pause(500)
    right.showColor(neopixel.colors(NeoPixelColors.Blue))
    cuteBot.singleheadlights(cuteBot.RGBLights.RGB_L, 0, 0, 255)
    basic.pause(500)
    right.showColor(neopixel.colors(NeoPixelColors.Black))
    cuteBot.singleheadlights(cuteBot.RGBLights.RGB_L, 0, 0, 0)
    basic.pause(500)
})
